Appease the non-git case
If this copy of zmap wasn't checked out from git, grab the version
string from the directory instead.

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -49,8 +49,10 @@ $(TARGETS):
 
 zmap: $(objects) 
 
+VERSION=`if [ -d ../.git ]; then echo \`git describe\`; else echo \`pwd | sed s:.*zmap-:: | sed s:/src::\`; fi`
 zmap_version.o:
-	echo "const char *zmap_version(void) {return \"`git describe`\";}" | $(CC) -x c -c - -o $@ $(CFLAGS)
+	@if [ -z "$(VERSION)" ]; then echo "Error determining zmap version"; exit 1; fi
+	echo "const char *zmap_version(void) {return \"$(VERSION)\";}" | $(CC) -x c -c - -o $@ $(CFLAGS)
 
 zopt_compat.o: zopt.c
 
